### ISSUE TITLE
Defaults: breaks combine: Nodes

### ISSUE THREAD

**Issue by yaaaaa** [yaaaaa/Reloaded-Origins#2]
To reproduce:
1) Put original offsets in folders:
![изображение](https://user-images.githubusercontent.com/11130958/65415419-8c3e0680-de17-11e9-9c19-9e4a278b162d.png)

![изображение](https://user-images.githubusercontent.com/11130958/65415431-8fd18d80-de17-11e9-8d98-f4dc2c9e97da.png)

2) Run make.cmd to build TO mod 
3) Change true to false in  `if (LoadField(d, "AddExtension", true)) `
Line 78 in Reloaded-Origins-master\engine\OpenRA.Mods.Common\Graphics\TilesetSpecificSpriteSequence.cs and Run make.cmd to build TO mod again or just rename file Reloaded-Origins-master\mods\yr\bits\sc\z\zl.png to zl.png.shp

4) Run launch-game.cmd to see the crash in sequense used combine:

This crash is not exist in d2k mod, this sequence and metadata loads from this png correctly.

**Comment by yaaaaa** [comment]
https://github.com/OpenRA/OpenRA/issues/17140

**Comment by yaaaaa** [comment]
if you "Change true to false in if (LoadField(d, "AddExtension", true))
Line 78 in Reloaded-Origins-master\engine\OpenRA.Mods.Common\Graphics\TilesetSpecificSpriteSequence.cs and Run make.cmd to build TO mod again" and not use AddExtension trait in e1 sequence, + add AddExtension: true to ALL other sequences of the mod, then game boot without errors, but when e1 soldier is trained in game, game crash: 

OpenRA engine version release-20190314
Red Alert 2 mod version {DEV_VERSION}
on map 982d0a37b50154eab6c3652b37301bb7966b6833 (The Alamo by Westwood Studios).
Date: 2019-09-23 12:09:31Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Ссылка на объект не указывает на экземпляр объекта.
   в OpenRA.Graphics.Animation.ScreenBounds(WorldRenderer wr, WPos pos, WVec offset, Single scale) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Graphics\Animation.cs:строка 72
   в OpenRA.Graphics.AnimationWithOffset.ScreenBounds(Actor self, WorldRenderer wr, Single scale) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Graphics\AnimationWithOffset.cs:строка 52
   в OpenRA.Mods.Common.Traits.Render.RenderSprites.<ScreenBounds>d__f.MoveNext() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Mods.Common\Traits\Render\RenderSprites.cs:строка 211
   в OpenRA.Actor.<Bounds>d__11.MoveNext() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Actor.cs:строка 197
   в System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   в OpenRA.Traits.ScreenMap.AggregateBounds(IEnumerable`1 screenBounds) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Traits\World\ScreenMap.cs:строка 225
   в OpenRA.Traits.ScreenMap.TickRender() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Traits\World\ScreenMap.cs:строка 265
   в OpenRA.World.TickRender(WorldRenderer wr) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\World.cs:строка 379
   в OpenRA.Game.<>c__DisplayClass23.<InnerLogicTick>b__20() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:строка 625
   в OpenRA.Sync.<>c__DisplayClass5.<RunUnsynced>b__4() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Sync.cs:строка 182
   в OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:строка 625
   в OpenRA.Game.LogicTick() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:строка 640
   в OpenRA.Game.Loop() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:строка 770
   в OpenRA.Game.Run() в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:строка 810
   в OpenRA.Game.InitializeAndRun(String[] args) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:строка 256
   в OpenRA.Program.Main(String[] args) в c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Support\Program.cs:строка 37

**Comment by alexeik** [comment]
![image](https://user-images.githubusercontent.com/318732/65454059-0dfc5700-de4d-11e9-9dae-879bfed1d87f.png)

вот так должна выглядеть папка для YR. 
нужно только эту папку заполнить.
RA2  не нужна.

**Comment by cookgreen** [comment]
I think there is a bug for sprite loaders, for now, openra use sprite loaders in the mod.yaml to load the sprite formats not the extension.
It will try to load the sprite with the order defined in the mod.yaml
so that means:
`SpriteFormats: ShpTS, TmpTS, ShpTD, PngSheet`

is different from 
`SpriteFormats: PngSheet, ShpTS, TmpTS, ShpTD`

So openra load the sprite by the sprite loader order defined in mod.yaml, not the extension. This is a big issue. I think that's why always load failed

In `SpriteLoader.cs`  
```
//should have sprite extension check, load sprite by using the correct sprite loader
foreach (var loader in loaders)
	if (loader.TryParseSprite(stream, out frames, out metadata))
		return frames;
```

@abcdefg30

**Comment by yaaaaa** [comment]
Removed PngSheet ot first place
`SpriteFormats: PngSheet, ShpTS, TmpTS, ShpTD`
, nothing changed.

> OpenRA engine version release-20190314
> Red Alert 2 mod version {DEV_VERSION}
> on map 3a94af24afc3d43b59eecdff309bbe44c5047644 (Pitch Point by Westwood Studios).
> Date: 2019-09-27 05:21:07Z
> Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
> Runtime Version: .NET CLR 4.0.30319.42000
> Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
>    at OpenRA.Graphics.Animation.ScreenBounds(WorldRenderer wr, WPos pos, WVec offset, Single scale) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Graphics\Animation.cs:line 72
>    at OpenRA.Graphics.AnimationWithOffset.ScreenBounds(Actor self, WorldRenderer wr, Single scale) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Graphics\AnimationWithOffset.cs:line 52
>    at OpenRA.Mods.Common.Traits.Render.RenderSprites.<ScreenBounds>d__f.MoveNext() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Mods.Common\Traits\Render\RenderSprites.cs:line 211
>    at OpenRA.Actor.<Bounds>d__11.MoveNext() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Actor.cs:line 197
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
>    at OpenRA.Traits.ScreenMap.AggregateBounds(IEnumerable`1 screenBounds) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Traits\World\ScreenMap.cs:line 225
>    at OpenRA.Traits.ScreenMap.TickRender() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Traits\World\ScreenMap.cs:line 265
>    at OpenRA.World.TickRender(WorldRenderer wr) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\World.cs:line 379
>    at OpenRA.Game.<>c__DisplayClass23.<InnerLogicTick>b__20() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:line 625
>    at OpenRA.Sync.<>c__DisplayClass5.<RunUnsynced>b__4() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Sync.cs:line 166
>    at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Sync.cs:line 182
>    at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Sync.cs:line 166
>    at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:line 625
>    at OpenRA.Game.LogicTick() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:line 640
>    at OpenRA.Game.Loop() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:line 770
>    at OpenRA.Game.Run() in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:line 810
>    at OpenRA.Game.InitializeAndRun(String[] args) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Game.cs:line 256
>    at OpenRA.Program.Main(String[] args) in c:\games\RTS\04.10.19\ra2-master\engine\OpenRA.Game\Support\Program.cs:line 37

@cookgreen its only if PNG in combine, look: https://github.com/OpenRA/OpenRA/issues/17140

@alexeik . работает даже без файла movmd03, у меня они же, только распакованы в ту же самую папку для извлечения ресурсов

**Comment by cookgreen** [comment]
ah

**Comment by cookgreen** [comment]
https://github.com/yaaaaa/Reloaded-Origins/pull/3

**Comment by yaaaaa** [comment]
Combine works correct without Defaults.

**Comment by cookgreen** [comment]
hey, long time no see!
